// Writes the public policy pages and their markdown copies from the one
// source, src/legal/policies.js.
//
//   node policies-build.mjs          write app/web/policies/*.html and docs/policies/*.md
//   node policies-build.mjs --check  exit 1 if any written file is out of date
//
// Google Play and the App Store need a privacy policy at a public URL, and Play
// needs the account-deletion route too. Host app/web/ on the owned domain
// (audit H-5) and point the store listings at policies/privacy.html and
// delete-account.html. CI runs --check so the hosted copy can't drift from the
// one in the app.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { POLICIES, POLICY_VERSION, LEGALLY_REVIEWED } from "./src/legal/policies.js";

const here = dirname(fileURLToPath(import.meta.url));
const WEB = join(here, "web", "policies");
const MD = join(here, "..", "docs", "policies");
const check = process.argv.includes("--check");

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const draftLine = "Draft awaiting review by a UAE lawyer. It describes how lili works today; the Arabic version will be the one that counts once it is published.";

const CSS = `
:root{--bg:#fff8f2;--card:#ffffff;--ink:#3b2a24;--muted:#6f5c55;--rule:#ead9cc;--accent:#8a4b35}
@media (prefers-color-scheme:dark){:root{--bg:#1b1412;--card:#251c19;--ink:#f2e4d8;--muted:#c4b0a4;--rule:#3b2e29;--accent:#e3a387}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
main{max-width:720px;margin:0 auto;padding:32px 20px 64px}
h1{font:600 30px/1.2 Georgia,"Times New Roman",serif;margin:0 0 6px}h2{font-size:19px;margin:28px 0 8px}
.ar{color:var(--muted);margin:0 0 18px}.lead{font-size:17px}.note{background:var(--card);border:1px solid var(--rule);border-radius:12px;padding:10px 14px;color:var(--muted);font-size:14px}
ul{padding-left:22px}li{margin:4px 0}a{color:var(--accent)}footer{margin-top:40px;color:var(--muted);font-size:14px;border-top:1px solid var(--rule);padding-top:14px}
nav ul{list-style:none;padding:0}nav li{margin:0;border-bottom:1px solid var(--rule)}nav a{display:block;padding:12px 0;text-decoration:none}nav small{display:block;color:var(--muted)}`;

const page = (title, body) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'">
<meta name="referrer" content="no-referrer">
<title>${esc(title)} · love it or leave it</title>
<!-- Generated by app/policies-build.mjs from app/src/legal/policies.js. Edit the source, not this file. -->
<style>${CSS}</style>
</head>
<body><main>
${body}
<footer>Version ${POLICY_VERSION}. <a href="index.html">All policies</a> · <a href="../delete-account.html">Delete your account</a></footer>
</main></body>
</html>
`;

const blockHtml = (b) => typeof b === "string"
  ? `<p>${esc(b)}</p>`
  : `<ul>\n${b.list.map((li) => `  <li>${esc(li)}</li>`).join("\n")}\n</ul>`;

const blockMd = (b) => typeof b === "string" ? b : b.list.map((li) => `- ${li}`).join("\n");

const out = new Map();
for (const p of POLICIES) {
  const status = LEGALLY_REVIEWED ? "" : `<p class="note">${esc(draftLine)}</p>\n`;
  out.set(join(WEB, `${p.id}.html`), page(p.title,
    `<h1>${esc(p.title)}</h1>\n<p class="ar" lang="ar" dir="rtl">${esc(p.titleAr)}</p>\n${status}<p class="lead">${esc(p.summary)}</p>\n` +
    p.sections.map((s) => `<h2>${esc(s.h)}</h2>\n${s.body.map(blockHtml).join("\n")}`).join("\n")));
  out.set(join(MD, `${p.id}.md`),
    `<!-- Generated by app/policies-build.mjs from app/src/legal/policies.js. Edit the source, not this file. -->\n\n` +
    `# ${p.title}\n\n` + (LEGALLY_REVIEWED ? "" : `> ${draftLine}\n\n`) + `${p.summary}\n\n` +
    p.sections.map((s) => `## ${s.h}\n\n${s.body.map(blockMd).join("\n\n")}`).join("\n\n") +
    `\n\n_Version ${POLICY_VERSION}._\n`);
}
out.set(join(WEB, "index.html"), page("Policies",
  `<h1>Policies</h1>\n<p class="ar" lang="ar" dir="rtl">السياسات</p>\n` +
  (LEGALLY_REVIEWED ? "" : `<p class="note">${esc(draftLine)}</p>\n`) +
  `<nav><ul>\n${POLICIES.map((p) => `  <li><a href="${p.id}.html">${esc(p.title)}<small>${esc(p.summary)}</small></a></li>`).join("\n")}\n</ul></nav>`));
out.set(join(MD, "README.md"),
  `<!-- Generated by app/policies-build.mjs from app/src/legal/policies.js. Edit the source, not this file. -->\n\n` +
  `# lili policies\n\n` + (LEGALLY_REVIEWED ? "" : `> ${draftLine}\n\n`) +
  `The same text is in the app (Profile → Privacy & Safety → All policies) and in \`app/web/policies/\` for hosting.\n\n` +
  POLICIES.map((p) => `- [${p.title}](${p.id}.md): ${p.summary}`).join("\n") + "\n");

let stale = [];
for (const [file, text] of out) {
  const current = existsSync(file) ? readFileSync(file, "utf8") : null;
  if (current === text) continue;
  if (check) { stale.push(file); continue; }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text);
}
if (check && stale.length) {
  console.error(`Policy pages are out of date. Run: node policies-build.mjs\n  ${stale.join("\n  ")}`);
  process.exit(1);
}
console.log(check ? `policy pages up to date (${out.size} files)` : `wrote ${out.size} policy files`);
