import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFileSync, existsSync } from "node:fs";
import { join, extname } from "node:path";
const M={".html":"text/html",".js":"text/javascript",".css":"text/css",".png":"image/png"};
const s=createServer((q,r)=>{let p=join("dist",decodeURIComponent(q.url.split("?")[0]));if(!existsSync(p)||p.endsWith("/"))p=join("dist","index.html");r.writeHead(200,{"Content-Type":M[extname(p)]||"text/plain"});r.end(readFileSync(p));});
await new Promise(r=>s.listen(4322,r));
const b=await chromium.launch(); const pg=await (await b.newContext({viewport:{width:393,height:852}})).newPage();
const t=async x=>{const e=pg.locator(`button:has-text("${x}")`).first();if(await e.count()){await e.click({timeout:1200}).catch(()=>{});await pg.waitForTimeout(220);return true;}return false;};
await pg.goto("http://localhost:4322/",{waitUntil:"networkidle"}); await pg.waitForTimeout(350);
await t("look around anyway"); await pg.locator("input").first().fill("1994");
await t("I agree to lili's Platform Terms"); await t("I agree to Privacy Notice");
await t("Agree and continue"); await t("Save choices"); await t("Shop Now"); await t("Skip");
await pg.waitForTimeout(300);
await pg.locator('button[aria-label="Sell"]').first().click(); await pg.waitForTimeout(300);
await pg.locator('input[placeholder*="Desert Rose"]').fill("Sahara");
await t("Selling from my own wardrobe"); await t("Continue");
const {sellerClausesFor}=await import("./src/compliance/agreements.js");
for (const c of sellerClausesFor("listing")) await t(c.title);
await t("Agree and open my shop"); await pg.waitForTimeout(450);
await t("List Item"); await t("Quick"); await t("Next"); await pg.waitForTimeout(220);
await pg.locator('input[placeholder*="Chanel Classic"]').fill("Chanel replica bag mirror quality");
await t("Next"); await pg.waitForTimeout(220);
console.log("after details Next -> inputs:", await pg.evaluate(()=>[...document.querySelectorAll("input,textarea")].map(x=>x.placeholder||x.inputMode||x.type)));
console.log("buttons:", await pg.evaluate(()=>[...document.querySelectorAll("button")].map(x=>x.textContent.trim().slice(0,24)).filter(Boolean).slice(0,8)));
const dec = pg.locator('input[inputmode="decimal"]').first();
if (await dec.count()===0) { console.log("NO PRICE FIELD — stopping"); process.exit(1); }
await dec.fill("400");
await pg.waitForTimeout(450);
const txt = await pg.evaluate(()=>document.body.innerText);
const btn = await pg.evaluate(()=>{const x=[...document.querySelectorAll("button")].find(y=>/Can't be listed|List Your Item/.test(y.textContent));return x?{t:x.textContent.trim().slice(0,28),d:x.disabled}:null;});
let p=0,f=0; const c=(l,ok,x="")=>{ok?p++:f++;console.log(`  ${ok?"✓":"✗"} ${l}${!ok&&x?"  "+x:""}`);};
console.log("\nQUICK LIST SCREENING\n");
c("the replica is refused", /Can't be listed/i.test(txt), txt.slice(0,140).replace(/\n/g," "));
c("publish is disabled", btn && btn.d===true, JSON.stringify(btn));
c("the seller is told why", /copy of a brand|replica/i.test(txt));
console.log(`\n${p} passed, ${f} failed\n`);
await b.close(); s.close(); process.exit(f?1:0);
