// Focused check: does Quick List now refuse a self-declared replica?
import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFileSync, existsSync } from "node:fs";
import { join, extname } from "node:path";
const M={".html":"text/html",".js":"text/javascript",".css":"text/css",".png":"image/png"};
const s=createServer((q,r)=>{let p=join("dist",decodeURIComponent(q.url.split("?")[0]));if(!existsSync(p)||p.endsWith("/"))p=join("dist","index.html");r.writeHead(200,{"Content-Type":M[extname(p)]||"text/plain"});r.end(readFileSync(p));});
await new Promise(r=>s.listen(4321,r));
const b=await chromium.launch(); const pg=await (await b.newContext({viewport:{width:393,height:852}})).newPage();
const t=async x=>{const e=pg.locator(`button:has-text("${x}")`).first();if(await e.count()){await e.click({timeout:1500}).catch(()=>{});await pg.waitForTimeout(230);return true;}return false;};
await pg.goto("http://localhost:4321/",{waitUntil:"networkidle"}); await pg.waitForTimeout(350);
await t("look around anyway"); await pg.locator("input").first().fill("1994");
await t("I agree to lili's Platform Terms"); await t("I agree to Privacy Notice");
await t("Agree and continue"); await t("Save choices"); await t("Shop Now"); await t("Skip");
await pg.waitForTimeout(350);
await pg.locator('button[aria-label="Sell"]').first().click(); await pg.waitForTimeout(350);
await pg.locator('input[placeholder*="Desert Rose"]').fill("Sahara");
await t("Selling from my own wardrobe"); await t("Continue");
const {sellerClausesFor}=await import("./src/compliance/agreements.js");
for (const c of sellerClausesFor("listing")) await t(c.title);
await t("Agree and open my shop"); await pg.waitForTimeout(500);
await t("List Item"); await t("Quick"); await t("Next"); await pg.waitForTimeout(250);
await pg.locator('input[placeholder*="Chanel Classic"]').fill("Chanel replica bag mirror quality");
await t("Next"); await pg.waitForTimeout(250);
await pg.locator('input[inputmode="decimal"]').first().fill("400");
await pg.waitForTimeout(500);
const txt = await pg.evaluate(()=>document.body.innerText);
const btn = await pg.evaluate(()=>{const b=[...document.querySelectorAll("button")].find(x=>/Can't be listed|List Your Item/.test(x.textContent));return b?{t:b.textContent.trim().slice(0,30),disabled:b.disabled}:null;});
let p=0,f=0; const c=(l,ok,x="")=>{ok?p++:f++;console.log(`  ${ok?"✓":"✗"} ${l}${!ok&&x?"  "+x:""}`);};
console.log("\nQUICK LIST SCREENING\n");
c("the replica is refused", /Can't be listed|can't be listed/i.test(txt), txt.slice(0,150).replace(/\n/g," "));
c("publish button is disabled", btn && btn.disabled===true, JSON.stringify(btn));
c("the reason is explained", /replica|copy of a brand/i.test(txt));
// and a clean listing still works
await pg.locator('input[placeholder*="Chanel Classic"]').count().then(async n=>{});
await t("Cancel");
await pg.waitForTimeout(300);
await t("List Item"); await t("Quick"); await t("Next"); await pg.waitForTimeout(250);
await pg.locator('input[placeholder*="Chanel Classic"]').fill("Silk Midi Dress");
await t("Next"); await pg.waitForTimeout(250);
await pg.locator('input[inputmode="decimal"]').first().fill("850");
await pg.waitForTimeout(500);
const btn2 = await pg.evaluate(()=>{const b=[...document.querySelectorAll("button")].find(x=>/List Your Item|Can't be listed/.test(x.textContent));return b?{t:b.textContent.trim().slice(0,30),disabled:b.disabled}:null;});
c("an honest listing is still publishable", btn2 && btn2.disabled===false, JSON.stringify(btn2));
console.log(`\n${p} passed, ${f} failed\n`);
await b.close(); s.close(); process.exit(f?1:0);
